@base_url=http://localhost:8080

# @name auth
GET {{base_url}}/token

###
@token = {{auth.response.body.$.token}}

POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "sleep"
}